version: '3'

services:
  vue_api:
    env_file:
      - .env
    container_name: vue_api
    build:
      context: .
      dockerfile: Dockerfile.loc
      args:
        user: laraveluser
        uid: 1000
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mysql1
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      ############################################
    command: bash -c "php artisan key:generate && php artisan migrate --force && apache2-foreground"
    networks:
      - my_network

networks:
  my_network:
    external:
      name: my_network