# fly.toml app configuration file generated for laravel-app-api on 2024-05-26T22:18:56-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'laravel-app-api'
primary_region = 'bog'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '7.4'

[env]
  APP_URL ="https://laravel-app-api.fly.dev"
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

  DB_CONNECTION = 'mysql'
  DB_DATABASE = 'b2yn39grdg6yv9qesywy'
  DB_HOST = 'b2yn39grdg6yv9qesywy-mysql.services.clever-cloud.com'
  DB_PASSWORD = 'iyolILlFQ0zU8JykqxUe'
  DB_USERNAME = 'u8f9xjjkj8pwjjtv'


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
